#!/bin/sh
# I put this script in /usr/bin and then run it as a pacman hook

# Run 'UpdateXPSWifiDrivers -h' for help and options/args

ExtractArchive() {
    echo "Unzipping archive..."
    /usr/bin/unzip ath10k-firmware-master.zip
    echo "Unzip successful.  Working on update..."
}

RunArchive() {
    sudo rm -R /lib/firmware/ath10k/QCA6174
    sudo cp -R ath10k-firmware-master/QCA6174/ /lib/firmware/ath10k/
    sudo mv /lib/firmware/ath10k/QCA6174/hw3.0/firmware-4.bin_WLAN.RM.2.0-00180-QCARMSWPZ-1 /lib/firmware/ath10k/QCA6174/hw3.0/firmware-4.bin
    sudo mv /lib/firmware/ath10k/QCA6174/hw3.0/4.4/firmware-6.bin_WLAN.RM.4.4-00022-QCARMSWPZ-2 /lib/firmware/ath10k/QCA6174/hw3.0/4.4/firmware-6.bin
    sudo mv /lib/firmware/ath10k/QCA6174/hw3.0/4.4.1/firmware-6.bin_WLAN.RM.4.4.1-00051-QCARMSWP-1 /lib/firmware/ath10k/QCA6174/hw3.0/4.4.1/firmware-6.bin
    sudo cp /lib/firmware/ath10k/QCA6174/hw3.0/4.4.1/firmware-6.bin /lib/firmware/ath10k/QCA6174/hw3.0/
}

DownloadFirmware() {
    /usr/bin/wget https://codeload.github.com/kvalo/ath10k-firmware/zip/master -O ath10k-firmware-master.zip
}

HelpMessage() {
    printf '%s\n' \
        "UpdateXPSWifiDrivers: Tool to update the Dell XPS-15/13 Wi-Fi drivers and fix dropping connection." \
        "" \
        "Arguments (Only takes one at a time):" \
        "   -l : Use ath10k-firmware-master zip in this directory" \
        "   -d : Download firmware to current directory (For -l)" \
        "   -h : Display this help message" \
        ""
}


if [ "$1" = "-h" ]; then
    # Printing the help menu
    HelpMessage
else
    if command -v wget unzip > /dev/null 2>&1 ; then
        echo "------ Fixing the XPS15 WiFi drivers ------"
        echo "Found wget and unzip..."
        echo "Downloading firmware..."

        if [ "$1" = "-l" ]; then
            # If zip is there locally local
            ExtractArchive
            RunArchive
            rm -rf ath10k-firmware-master/
            echo "------ Fixed the XPS15 WiFi drivers ------"
        elif [ "$1" = "-d" ]; then
            # For just downloading the zip locally
            DownloadFirmware
        elif DownloadFirmware; then
            # If no args provided: download and update drivers together
            ExtractArchive
            RunArchive
            echo "Cleaning up..."
            rm ath10k-firmware-master.zip
            rm -rf ath10k-firmware-master/
            echo "------ Fixed the XPS15 WiFi drivers ------"
        fi
    else
        echo "Please install wget and unzip before use."
    fi
fi
