# Rest in peace Vim <3 I still love you but NeoVim just is needed with all my plugins for performance
alias vim='nvim'
alias v='vim'
alias suv='sudo vim'

# Basic shell stuff
# Enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls -hN --color=auto --group-directories-first'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# Some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias ld='ls -d .*/ */'
alias mv='mv -i' # Ask to confirm
alias rm='rm -i' # Ask to confirm

# NVIDIA and Optimus Manager
alias pro='__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia'
alias mb='sudo su -c "echo 12 >/sys/class/backlight/intel_backlight/brightness"' # Go to minimum brightness
alias nv='optimus-manager --switch nvidia'
alias intl='optimus-manager --switch intel'
alias gpu='glxinfo | grep renderer'
alias bat='upower -i $(upower -e | grep BAT) | awk "/percentage/ {print $2}"'

# MongoDB
alias startMongo='sudo systemctl start mongodb.service'
alias stopMongo='sudo systemctl stop mongodb.service'

# Ornamentation
alias weather='curl wttr.in'
alias aunews='curl au.getnews.tech'
alias usnews='curl us.getnews.tech'
alias starwars='telnet towel.blinkenlights.nl'
setDribbblishTheme() {
    # Spotify themeing
    spicetify config current_theme Dribbblish color_scheme "$1" && spicetify apply
}
setupDribblish() {
    # Spotify
    cd "$(dirname "$(spicetify -c)")/Themes/Dribbblish" || return
    cp dribbblish.js ../../Extensions
    spicetify config extensions dribbblish.js
    spicetify config current_theme Dribbblish color_scheme base
    spicetify config inject_css 1 replace_colors 1 overwrite_assets 1
    spicetify apply
}

# In case XDG_CONFIG_HOME has been unset
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"

# All edits
alias eac='vim $XDG_CONFIG_HOME/alacritty/alacritty.yml'
alias eaw='cd $XDG_CONFIG_HOME/awesome/ && vim'
alias ed='cd $XDG_CONFIG_HOME/dwm/ && vim'
alias edb='cd $XDG_CONFIG_HOME/dwmblocks/ && vim'
alias edst='vim $XDG_CONFIG_HOME/dunst/dunstrc'
alias ei='vim $HOME/.xinitrc'
alias es='vim $XDG_CONFIG_HOME/startup-apps'
alias er='vim $XDG_CONFIG_HOME/redshift/redshift.conf'
alias eal='vim $XDG_CONFIG_HOME/bash/bash_aliases'
alias eb='vim $HOME/.bashrc'
alias ev='vim $HOME/.vimrc'
alias td='vim $HOME/Documents/ToDoList.txt'
alias el='sudo vim /etc/lightdm/lightdm.conf'
alias ee='vim $HOME/.doom.d/init.el'
alias ep='vim $HOME/.profile'

# All code
alias smi='sudo make install' # Handy for dwm and suckless software

# Utility
alias update-grub='sudo grub-mkconfig -o /boot/grub/grub.cfg'
alias x='exit'
alias reload='source $HOME/.bashrc'
alias delOrphans='sudo /bin/pacman -Rns $(pacman -Qtdq)' # Remove orphaned packages
alias yay!='yay' # YAY!!!!!!!!!
alias pacman='yay'
alias pls='sudo'
alias open='xdg-open'
alias g='git'
alias wdil='history | grep'
alias debugxapp='G_MESSAGES_DEBUG=X11Helper'
# Active monitor function from here: https://unix.stackexchange.com/questions/203844/how-to-find-out-the-current-active-xserver-display-number
whichActiveMon() {
    for p in $(pgrep -t $(cat /sys/class/tty/tty0/active));
    do
        d=$(awk -v RS='\0' -F= '$1=="DISPLAY" {print $2}' /proc/$p/environ 2>/dev/null);
        [[ -n $d ]] && break;
    done;
    echo $d
}

# WIFI
alias getRegularWifiPassword='sudo grep psk= /etc/NetworkManager/system-connections/limit56farce59umbra.nmconnection'
alias getLANIP="ip a s wlp2s0 | awk -F '[/ ]+' '/inet / {print $3}'"
alias resetPiSSH='ssh-keygen -R 192.168.87.109'
alias scanwifi='sudo nmap -sS -O'

# System
alias startBluetooth='sudo systemctl start bluetooth.service'

# Instant CD's
alias documents='cd $HOME/Documents'
alias docs='cd $HOME/Documents'
alias images='cd $HOME/Pictures'
alias videos='cd $HOME/Videos'
alias dls='cd $HOME/Downloads'
alias uni='cd $HOME/Documents/Uni/7Sem'
alias lec='cd $HOME/Documents/Uni/7Sem/Lectures'
alias cgp='cd $HOME/Documents/Uni/7Sem/Lectures/CGP'
alias ml='cd $HOME/Documents/Uni/7Sem/Lectures/ML'
alias ux='cd $HOME/Documents/Uni/7Sem/Lectures/UX'
alias res='cd $HOME/Documents/Uni/7Sem/Project/Research'
alias resn='cd $HOME/Documents/Uni/7Sem/Project/Notes'
alias uniVideos='cd $HOME/Videos/Sem6/'
alias rscript='cd $HOME/.config/REAPER/Scripts/Own\ Scripts/Night-REAPER-Scripts'

# Dotfiles
alias config='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
alias c='config'
alias seeCommitDiff='config diff --cached origin/master'
alias status='config status'

# Currency conversion (cconv {amount} {from} {to}) (Country codes must be capital)
cconv () {
    qalc -t "$1" "$2" to "$3"
}

# Make directory and CD
mkcdir () {
    mkdir -p -- "$1" &&
        cd -P -- "$1" ||
        exit | return
}

# Time functions (Credit: https://superuser.com/a/611582)
countdown () {
    date1=$(($(date +%s) + $1));
    while [ "$date1" -ge "$(date +%s)" ]; do
        echo -ne "$(date -u --date @$(($date1 - `date +%s`)) +%H:%M:%S)\r";
        sleep 0.1
    done
}

stopwatch () {
    date1=$(date +%s);
    # 24 = q ; 65 = SPACE
    while true; do
        echo -ne "$(date -u --date @$((`date +%s` - $date1)) +%H:%M:%S)\r";
        sleep 0.1
    done
}

# Get all aliases
alias aliases='head -n -4 $XDG_CONFIG_HOME/bash/.bash_aliases | less'
alias aliasCommand='tail -n 3 $XDG_CONFIG_HOME/bash/.bash_aliases' # Get the get aliases command
