#!/bin/sh

# All the startup applications and stuff

picom -b --experimental-backends --dbus

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
eval "$(gnome-keyring-daemon -s --components=pkcs11,secrets,ssh,gpg)"

xrdb "$HOME/.Xresources"

nm-applet &
blueman-applet &

pulseeffects --gapplication-service &

redshift &

feh --bg-fill "$XDG_CONFIG_HOME/wallpaper.jpg"
