#!/bin/sh

# All the startup applications and stuff

picom -b --experimental-backends --dbus --backend glx --blur-method dual_kawase # Compositor (Blur)

# The password popup prompt for some things
/usr/lib/polkit-kde-authentication-agent-1 &

xrdb "$HOME/.Xresources"

nm-applet & # Wifi applet in systray
# blueman-applet & # Bluetooth applet in systray
# pulseeffects --gapplication-service &
# qjackctl & # JACK GUI control

redshift & # Blue light filter

feh --no-fehbg --bg-fill "$XDG_CONFIG_HOME/wallpaper.jpg" # Background

dunst & # Notifications
dwmblocks & # Status bar

#timedatectl set-ntp true
